In [2]:
from scipy.optimize import linprog
import numpy as np

# 3.2.2.b) Linear Programming - ChevyShev

In [31]:
x = np.array([29.1, 48.2, 72.7, 92.0, 118, 140, 165, 199])
y = np.array([0.0493, 0.0821, 0.123, 0.154, 0.197, 0.234, 0.274, 0.328])

# Set what to minimize. from [r, a, b] we are minimizing r. So [1,0,0]
c = [1,0,0]

# Define A
A = np.zeros((16,3))
for i, xi in zip(range(0, 16, 2), x):
    A[i] = np.array([-1, -xi, -1])
    A[i+1] = np.array([-1, xi, 1])

# Define b
b = np.zeros((16,1))
for i, yi in zip(range(0, 16, 2), y):
    b[i] = np.array(-yi)
    b[i+1] = np.array(yi)

# Set Bounds
r_bounds = (None, None)
a_bounds = (None, None)
b_bounds = (None, None)

res = linprog(c, A_ub=A, b_ub=b, bounds=[r_bounds, a_bounds, b_bounds])
print("Minimum r : {}, a : {}, b : {}".format(res['x'][0],res['x'][1],res['x'][2]))

Minimum r : 0.0013911123575149342, a : 0.0016403766921022772, b : 0.0029561501342121183


# 3.2.3) Linear Programming - ChevyShev

In [36]:
x = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
y = np.array([0.06, 0.12, 0.36, 0.65, 0.95])

# Set what to minimize. from [r, c1, c2, c3] we are minimizing r. So [1,0,0,0]
c = [1,0,0,0]

# Define A
A = np.zeros((10,4))
for i, xi in zip(range(0, 10, 2), x):
    A[i] = np.array([-1, -xi**2, -xi,-1])
    A[i+1] = np.array([-1, xi**2, xi, 1])

# Define b
b = np.zeros((10,1))
for i, yi in zip(range(0, 10, 2), y):
    b[i] = np.array(-yi)
    b[i+1] = np.array(yi)

# Set Bounds
r_bounds = (None, None)
c1_bounds = (None, None)
c2_bounds = (None, None)
c3_bounds = (None, None)

res = linprog(c, A_ub=A, b_ub=b, bounds=[r_bounds, c1_bounds, c2_bounds, c3_bounds])
print("Minimum r : {}, c1 : {}, c2 : {}, c3 : {}".format(res['x'][0],res['x'][1],res['x'][2], res['x'][3]))

Minimum r : 0.028333333405751615, c1 : 3.999999999003919, c2 : -0.03333333273638284, c3 : -0.005000000013919814


# 3.3.4 : Least Square Criterion

In [42]:
t = np.array([7, 14, 21, 28, 35, 42])
P = np.array([8, 41, 133, 250, 280, 297])
lnP = np.log(P)
t_square = t**2

In [2]:
A = np.array([[12, 294], [294, 8918]])
ans = np.linalg.inv(A) @ np.array([[55.07], [1520.4]])
a_prime = ans[0]
b = ans[1]
a = np.exp(a_prime)
print("a : {}, b : {}".format(a, b))

a : [8.53065944], b : [0.09981633]


In [39]:
sum(t) * 2

294

In [41]:
sum(lnP) * 2

55.06669079288018

In [43]:
2*sum(t_square)

8918

In [44]:
2 * sum(t*lnP)

1520.397446118112

# 3.3.8 : Least Square Criterion

In [53]:
# a

x = np.array([5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) * 1000
y = np.array([0, 19, 57, 94, 134, 173, 216, 256, 297, 343, 390]) * 100000

sig_xy = sum(x * y)
sig_x_square = sum(x**2)
print(sig_xy / sig_x_square)

370.33095392602206


In [55]:
# b

x = np.array([5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) * 1000
y = np.array([0, 19, 57, 94, 134, 173, 216, 256, 297, 343, 390]) * 100000

print(2*sum(x**2), 2 * sum(x), 2*sum(x*y), 2*sum(y))

A = np.array([ [2*sum(x**2), 2 * sum(x)], [2 * sum(x), 22] ])

ans = np.linalg.inv(A) @ np.array([[2*sum(x*y)], [2*sum(y)]])

a = ans[0]
b = ans[1]

print("a : {}, b : {}".format(a, b))

77050000000 1110000 28534000000000 395800000
a : [406.93304536], b : [-2540712.74298055]


In [57]:
# c

x = np.array([5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) # * 1000
y = np.array([0, 19, 57, 94, 134, 173, 216, 256, 297, 343, 390]) # * 100000

print(sum(x**2 * y), sum(x**4), sum(x**2 * y)/sum(x**4))

11367300 253330625 0.04487140076333053


# 3.4.7
### Least Square Criterion

In [65]:
# a

l = np.array([14.5, 12.5, 17.25, 14.5, 12.625, 17.75, 14.125, 12.625])
W = np.array([27, 17, 41, 26, 17, 49, 23, 16])

k = sum(W*l**3)/sum(l**6)
print("k :", k)
W_pred = (k*l**3).round(3)
print(W_pred)

print(sum((W - W_pred)**2))

k : 0.008436760675206318
[25.721 16.478 43.305 25.721 16.977 47.181 23.776 16.977]
12.16518600000001


In [68]:
# b

l = np.array([14.5, 12.5, 17.25, 14.5, 12.625, 17.75, 14.125, 12.625])
W = np.array([27, 17, 41, 26, 17, 49, 23, 16])
g = np.array([9.75, 8.375, 11, 9.75, 8.5, 12.5, 9, 8.5])

k = sum(W*l*g**2) / sum(l**2 * g **4)
print("k :", k)

W_pred = (k * l * g ** 2).round(3)
print(W_pred)

print(sum((W - W_pred)**2))

k : 0.018675110215167733
[25.742 16.374 38.98  25.742 17.035 51.794 21.367 17.035]
17.666978999999994


### CAC

In [4]:
l = np.array([14.5, 12.5, 17.25, 14.5, 12.625, 17.75, 14.125, 12.625])
W = np.array([27, 17, 41, 26, 17, 49, 23, 16])

# Set what to minimize.
c = [1,0]

# Define A
A = np.zeros((16,2))
for i, xi in zip(range(0, 16, 2), l):
    A[i] = np.array([-1, -xi**3])
    A[i+1] = np.array([-1, xi**3])

# Define b
b = np.zeros((16,1))
for i, yi in zip(range(0, 16, 2), W):
    b[i] = np.array(-yi)
    b[i+1] = np.array(yi)

# Set Bounds
r_bounds = (None, None)
c_bounds = (None, None)

res = linprog(c, A_ub=A, b_ub=b, bounds=[r_bounds, c_bounds])
print("Minimum r : {}, k : {}".format(res['x'][0],res['x'][1]))

Minimum r : 2.072477492176346, k : 0.008391363882313208


# 3.4.8

## LSC

In [70]:
# model 1
l = np.array([14.5, 12.5, 17.25, 14.5, 12.625, 17.75, 14.125, 12.625])
W = np.array([27, 17, 41, 26, 17, 49, 23, 16])
g = np.array([9.75, 8.375, 11, 9.75, 8.5, 12.5, 9, 8.5])

c = sum(W*g**3)/sum(g**6)
print('c :',c)

W_pred = (c*g**3).round(3)
print(W_pred)

print(sum((W - W_pred)**2))

c : 0.02757821830681667
[25.561 16.2   36.707 25.561 16.936 53.864 20.105 16.936]
54.25300399999997


In [71]:
# model 2
l = np.array([14.5, 12.5, 17.25, 14.5, 12.625, 17.75, 14.125, 12.625])
W = np.array([27, 17, 41, 26, 17, 49, 23, 16])
g = np.array([9.75, 8.375, 11, 9.75, 8.5, 12.5, 9, 8.5])

k = sum(W*g*l**2)/sum(l**4 * g**2)
print('k :',k)

W_pred = (k*g*l**2).round(3)
print(W_pred)

print(sum((W - W_pred)**2))

k : 0.012583877271935714
[25.796 16.467 41.189 25.796 17.049 49.559 22.596 17.049]
3.389540999999999


## CAC

In [2]:
# Model 1

l = np.array([14.5, 12.5, 17.25, 14.5, 12.625, 17.75, 14.125, 12.625])
W = np.array([27, 17, 41, 26, 17, 49, 23, 16])
g = np.array([9.75, 8.375, 11, 9.75, 8.5, 12.5, 9, 8.5])

# Set what to minimize.
c = [1,0]

# Define A
A = np.zeros((16,2))
for i, xi in zip(range(0, 16, 2), g):
    A[i] = np.array([-1, -xi**3])
    A[i+1] = np.array([-1, xi**3])

# Define b
b = np.zeros((16,1))
for i, yi in zip(range(0, 16, 2), W):
    b[i] = np.array(-yi)
    b[i+1] = np.array(yi)

# Set Bounds
r_bounds = (None, None)
c_bounds = (None, None)

res = linprog(c, A_ub=A, b_ub=b, bounds=[r_bounds, c_bounds])
print("Minimum r : {}, c : {}".format(res['x'][0],res['x'][1]))

Minimum r : 4.524530885879084, c : 0.027404559792612027


In [5]:
# Model 2

l = np.array([14.5, 12.5, 17.25, 14.5, 12.625, 17.75, 14.125, 12.625])
W = np.array([27, 17, 41, 26, 17, 49, 23, 16])
g = np.array([9.75, 8.375, 11, 9.75, 8.5, 12.5, 9, 8.5])

# Set what to minimize.
c = [1,0]

# Define A
A = np.zeros((16,2))
for i, gi, li in zip(range(0, 16, 2), g, l):
    A[i] = np.array([-1, -li*gi**2])
    A[i+1] = np.array([-1, li*gi**2])

# Define b
b = np.zeros((16,1))
for i, yi in zip(range(0, 16, 2), W):
    b[i] = np.array(-yi)
    b[i+1] = np.array(yi)

# Set Bounds
r_bounds = (None, None)
c_bounds = (None, None)

res = linprog(c, A_ub=A, b_ub=b, bounds=[r_bounds, c_bounds])
print("Minimum r : {}, k : {}".format(res['x'][0],res['x'][1]))

Minimum r : 2.352689326262941, k : 0.01851589916869445


In [4]:
# Model 2

l = np.array([14.5, 12.5, 17.25, 14.5, 12.625, 17.75, 14.125, 12.625])
W = np.array([27, 17, 41, 26, 17, 49, 23, 16])
g = np.array([9.75, 8.375, 11, 9.75, 8.5, 12.5, 9, 8.5])

# Set what to minimize.
c = [1,0]

# Define A
A = np.zeros((16,2))
for i, gi, li in zip(range(0, 16, 2), g, l):
    A[i] = np.array([-1, -gi*li**2])
    A[i+1] = np.array([-1, gi*li**2])

# Define b
b = np.zeros((16,1))
for i, yi in zip(range(0, 16, 2), W):
    b[i] = np.array(-yi)
    b[i+1] = np.array(yi)

# Set Bounds
r_bounds = (None, None)
c_bounds = (None, None)

res = linprog(c, A_ub=A, b_ub=b, bounds=[r_bounds, c_bounds])
print("Minimum r : {}, k : {}".format(res['x'][0],res['x'][1]))

Minimum r : 1.1105484283291576, k : 0.012629385811633087
