In [1]:
%matplotlib inline
import numpy as np

# Eigenvalues and Eigenvectors

In [4]:
A = np.random.rand(3,3)
# Make A symmetric
A = A + A.T
print(A)

eigval, eigvec = np.linalg.eig(A)

# print(eigval)
# print(eigvec)
lambda1 = eigval[0]
lambda2 = eigval[1]
lambda3 = eigval[2]

u1 = eigvec[:,0]
u2 = eigvec[:,1]
u3 = eigvec[:,2]
print("="*40)
print("eigenvalue : {}, eigenvector : {}".format(lambda1, u1))
print("eigenvalue : {}, eigenvector : {}".format(lambda2, u2))
print("eigenvalue : {}, eigenvector : {}".format(lambda3, u3))

[[1.50424531 0.58168334 0.44793388]
 [0.58168334 1.2990317  1.52226769]
 [0.44793388 1.52226769 0.5211125 ]]
[[ 0.47224921  0.88146378  0.00150907]
 [ 0.69642524 -0.3720632  -0.61364555]
 [ 0.54034486 -0.29084459  0.78958018]]
[0.47224921 0.88146378 0.00150907] [0.47224921 0.69642524 0.54034486]
eigenvalue : 2.874576288636794, eigenvector : [0.47224921 0.69642524 0.54034486]
eigenvalue : 1.1109198998702134, eigenvector : [ 0.88146378 -0.3720632  -0.29084459]
eigenvalue : -0.6611066764199559, eigenvector : [ 0.00150907 -0.61364555  0.78958018]


In [5]:
B = np.array([ [2,1], [0,2] ])
eigval, eigvec = np.linalg.eig(B)
print(eigval, eigvec)

[2. 2.] [[ 1.0000000e+00 -1.0000000e+00]
 [ 0.0000000e+00  4.4408921e-16]]


In [4]:
n = 2000
A = np.random.rand(n,n)
# Make A symmetric
A = A + A.T

# if put high number in n, it takes a while, longer than inverse. EVP are the most complex thing to solve.
eigval, eigvec = np.linalg.eig(A)
print(eigval)

print("how many eigval {}, same as n : {}".format(len(eigval), n))

[ 2.00054563e+03 -3.63616981e+01 -3.61712137e+01 ...  8.04428237e-01
 -1.46677203e-02 -1.39585514e+00]
how many eigval 2000, same as n : 2000
