In [1]:
import numpy as np

# Q1
### (a) calculate dot product

In [2]:
a = np.array([2,-3,7])
b = np.array([-4,1,0])
c = np.array([5,-1,9])
d = np.array([0,0,2])

# Use np.dot to calculate
adotb = np.dot(a,b)
cdotd = np.dot(c,d)
print("adotb :", adotb,"cdotd :", cdotd)

adotb : -11 cdotd : 18


### (b) the angles which A cross B makes with the x,y,z axes

In [3]:
acrossb = np.cross(a,b)
x,y,z = np.array([1,0,0]), np.array([0,1,0]), np.array([0,0,1])

angle1 = np.arccos(np.dot(acrossb, x) / np.linalg.norm(acrossb) * np.linalg.norm(x))
angle2 = np.arccos(np.dot(acrossb, y) / np.linalg.norm(acrossb) * np.linalg.norm(y))
angle3 = np.arccos(np.dot(acrossb, z) / np.linalg.norm(acrossb) * np.linalg.norm(z))

print("A cross B :", acrossb)

print("\nx axis")
print("rad:", angle1, ", degree", angle1*180/np.pi)

print("y axis")
print("rad:", angle2, ", degree", angle2*180/np.pi)

print("z axis")
print("rad:", angle3, ", degree", angle3*180/np.pi)

A cross B : [ -7 -28 -10]

x axis
rad: 1.802020934400567 , degree 103.24819413537348
y axis
rad: 2.730485267782634 , degree 156.44528186659335
z axis
rad: 1.9043313752416218 , degree 109.11015059568881


### (c) Unit vector in the direction of B cross D

In [4]:
bcrossd = np.cross(b,d)
unit = bcrossd / np.linalg.norm(bcrossd)
print("cross product :", bcrossd,"unit vector :", unit)

# check if it is unit vector
print(np.linalg.norm(unit))

cross product : [2 8 0] unit vector : [0.24253563 0.9701425  0.        ]
1.0


### (d) the vector with the largest magnitude

In [5]:
# create a list of vector a,b,c,d
vector_list = [a,b,c,d]
# create a list to get the magnitudes of vectors
vector_magnitude_list = []
# create a list of names to show later
names = ['a', 'b', 'c', 'd']

# use 'for' to get values of magnitude into vector_magnitude_list
for i in range(len(vector_list)):
    vector_magnitude_list.append(np.linalg.norm(vector_list[i]))

# use 'max' to get the largest magnitude
largest = max(vector_magnitude_list)

# print the largest vector name, the vector, magnitude
print("Largest Vector :",names[vector_magnitude_list.index(largest)], \
      vector_list[vector_magnitude_list.index(largest)],"Magnitude :", largest)



Largest Vector : c [ 5 -1  9] Magnitude : 10.344080432788601


# Q2
### (a) print a,b,ab

In [6]:
# use arange to create matrix then reshape to make it into the shape I want
a = np.arange(12); a = a.reshape(3,4); print("a:", a, sep = '\n')
b = np.arange(8); b = b.reshape(4,2); print("b:",b, sep = '\n')
# Use 'matmul' for matrix multiplication
print("ab:", np.matmul(a,b), sep = '\n')

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
ab:
[[ 28  34]
 [ 76  98]
 [124 162]]


### (b) Is it possible to do the multiplication aaT?

In [7]:
# Use try/except to see if the multiplication work
try:
    np.matmul(a, a.T)
    print("It is possible.")
    print("shape of a :", a.shape, "shape of a transposed :", a.T.shape)
except:
    print("It is not possible.")
    print("shape of a :", a.shape, "shape of a transposed :", a.T.shape)

It is possible.
shape of a : (3, 4) shape of a transposed : (4, 3)


- to do a matrix multiplication, the column value of former matrix and the row value of later matrix should be the same. Matrix a has shape of 3,4 and a transposed has a shape of 4,3. 

### (c) show that (ab).T = (b.T) (a.T)

In [8]:
# check if all elements are the same
print(np.matmul(a,b).T == np.matmul(b.T, a.T))

[[ True  True  True]
 [ True  True  True]]


### (d) create two square matrices c,d of equal size and show that (cd)inverse = (d)inverse (c)inverse

In [9]:
c = np.arange(4); c = c.reshape(2,2); d = np.arange(4,8); d = d.reshape(2,2)
cd = np.matmul(c,d)

# set cutoff value useing round(decimals = 10). Inverse matrix is obtained through iterations, so it can't be exact.
print(np.linalg.inv(cd).round(10) == np.matmul(np.linalg.inv(d), np.linalg.inv(c)).round(10))

[[ True  True]
 [ True  True]]


### (e) show that (c)inverse.T = (c.T)inverse

In [10]:
print(np.linalg.inv(c).round(10).T == np.linalg.inv(c.T).round(10))

[[ True  True]
 [ True  True]]


# Q3

In [11]:
# Coefficient Matrix A
A = np.array([ [2,0.7,-3.5,7,-0.5], [-1.2, 2.7, 0, -3, -2.5], [1, 1, -1, -1, 1], [2.9, 0, 0, 0, 7.5], [0, 0, 1.8, -2.7, -5.5] ])
# Constant Vector b
b = np.array([2, -17, 5, 0 ,-11])
# Unknown Variable Vector x
x = np.linalg.inv(A)@b

# Answer to the system of linear equations:
for i in range(5):
    print('x', i+1, ' = ', x[i], sep = '')

# Checking the answer
print("")
for i in range(A.shape[0]):
    print("Substituting for the row{} in matrix A with vector x".format(i))
    print(np.dot(A[i,:], x).round(10) == b[i])
    

x1 = -0.56501823759602
x2 = -11.34361865307503
x3 = -12.191518913957196
x4 = -4.498644258176723
x5 = 0.21847371853712771

Substituting for the row0 in matrix A with vector x
True
Substituting for the row1 in matrix A with vector x
True
Substituting for the row2 in matrix A with vector x
True
Substituting for the row3 in matrix A with vector x
True
Substituting for the row4 in matrix A with vector x
True
