In [1]:
import numpy as np

# Matrix and Vectors
1. Shape of A = ( # of rows (m) , # of columns (n) )
- if m = n, square matrix : very important in engineering problems
- else, non-square matrix : important for curve-fitting (broadly)  
2. For a matrix A(m,n) - can access to each elements with []
- A[0,0] : row 1 column 1 , A[1,0] : row 2 column 1 , ...
3. Diagonal matrix : all values are zero except the diagonal elements in a square matrix A(n,n)
- written A[i,j] == 0 at i!= j
4. Identity matrix : diagonal matrix w/ only 1s in the element : A[i,j] == 0 at i!= j, A[i,j] == 1 at i = j
- IM = M = MI
5. Lower triangular matrix : lower triangular region of matrix is non-zero while others are zero (important in algoritmic things)
- A[i,j] == 0 at i < j, A[i,j] != 0 at i >= j
6. Symmetric matrix 
- A[i,j] == A[j,i]
- A.transpose = A
7. Transpose of matrix
- B = A.Transpose, A[i,j] = B[j,i]

# Inverse Matrix
1. Matrix Multiplication
- A(m,n), B(p,q) : to be able to perform multiplication, n = p
- C = A x B -> C(m,q)
2. Inverse Matrix is only discussed for square matrix ( can obtain inverse from non-square, called sudo-inverse)
- Def) A(inverse) x A(n,n) = A(n,n) x A(inverse) = I
- Determinant of A != 0 for inverse to exist

In [14]:
# create a square matrix A, non square matrix B, C
A = np.arange(1,5); A = A.reshape(2,2)
B = np.random.rand(2,5).round(2)
C = np.random.rand(5,6).round(2)
print(A,B,C, sep = '\n')

[[1 2]
 [3 4]]
[[0.53 0.46 0.93 0.49 0.53]
 [0.1  0.77 0.76 0.05 0.5 ]]
[[0.82 0.04 0.72 0.14 0.42 0.63]
 [0.82 0.65 0.73 0.81 0.93 0.45]
 [0.53 0.72 0.68 0.47 0.32 0.32]
 [0.47 0.67 0.37 0.92 0.44 0.7 ]
 [0.75 0.37 0.73 0.01 0.53 0.83]]


In [15]:
# col of B = row of C, so
D = B@C
print("B x C = D, shape of D :", D.shape)

B x C = D, shape of D : (2, 6)


In [16]:
# create identity matrix : eye
I = np.eye(2)
print("Identity Matrix", I, sep = '\n')

Identity Matrix
[[1. 0.]
 [0. 1.]]


In [17]:
# Transpose of B
print(B, B.T, sep = '\n')

[[0.53 0.46 0.93 0.49 0.53]
 [0.1  0.77 0.76 0.05 0.5 ]]
[[0.53 0.1 ]
 [0.46 0.77]
 [0.93 0.76]
 [0.49 0.05]
 [0.53 0.5 ]]


In [19]:
# Create a symmetrix matrix
E = np.random.rand(3,3)
print(E)
F = E + E.T
print("for random matrix E, E + E.T is symmetric.", F, sep = '\n')

[[0.7840813  0.17486515 0.82422356]
 [0.28507045 0.04039855 0.95155801]
 [0.59606926 0.13074755 0.06130392]]
for random matrix E, E + E.T is symmetric.
[[1.5681626  0.4599356  1.42029282]
 [0.4599356  0.0807971  1.08230556]
 [1.42029282 1.08230556 0.12260785]]


In [21]:
# Inverse of F
Finv = np.linalg.inv(F)
print((F@Finv).round(10))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# How to solve system of linear equations
- system of linear equations  
2x + 5y = -10  
3x - 10y = 2
- matrix form : Ax = B  
solution is : x = A(inverse) x B
- Being able to calculate inverse is the key to solving engineering problems

In [23]:
A = np.array([[2,5], [3,-10]])
B = np.array([[-10], [2]])
x = np.linalg.inv(A)@B
print(x)

[[-2.57142857]
 [-0.97142857]]


In [25]:
# slightly more complicated example
# 2x+5y = -10
# 3x-10y+7z = 23
# -5x+8z = -6
A = np.array([[2,5,0],[3,-10,7],[-5,0,8]])
B = np.array([[-10], [23], [-6]])
x = np.linalg.inv(A)@B
print(x)

[[ 0.72527473]
 [-2.29010989]
 [-0.2967033 ]]
