In [7]:
import numpy as np

# Create Vectors
## create a row vector

In [8]:
R = np.array([[1,2,3]]) # two brakets to create matrix
print("R", R, np.shape(R), sep = '\n')

R
[[1 2 3]]
(1, 3)


## create a column vector

In [9]:
C = np.array([[5],[6],[7]])
print("C", C, np.shape(C), sep = '\n')

C
[[5]
 [6]
 [7]]
(3, 1)


## sum of vectors

In [11]:
A = np.array([[-10, 7, 30]])
print("Sum :", A+R)

Sum : [[-9  9 33]]


## 1-D vectors(not recommended!)

In [12]:
D = np.array([10,2,5])
print("D", D, np.shape(D), sep = '\n')

D
[1 2 3]
(3,)


## Calculate the magnitude of R

In [21]:
print(R);print(A)
print(R[0,0], R[0,1], R[0,2])

# Hard Coding
Rmag = 0
for i in range(R.shape[1]):
    Rmag += R[0,i]**2
    
Rmag = np.sqrt(Rmag)
print(Rmag)

# Use dot and sqrt
# Rsquared = np.dot(R, R)
# print(np.sqrt(Rsquared))

# Use library np.linalg.norm
print(np.linalg.norm(R))

T = np.array([[2,3,4,5,6,7,8,9,10]])
print(np.shape(T), np.linalg.norm(T))

[[1 2 3]]
[[-10   7  30]]
1 2 3
3.7416573867739413
3.7416573867739413
(1, 9) 19.595917942265423


## Dot and cross products

In [28]:
# Dot
print("Dot Product")
A = np.array([[1,2,3]])
B = np.array([[-1,8,13]])

try:
    print(np.dot(A,B))
except:
    print("python only calculate dot in vectors!! Use 1-D array")
    A = np.array([1,2,3])
    B = np.array([-1,8,13])
    print(np.dot(A,B))
    
# Cross
print("Cross Product, btw cross product can take matix in calculation")
C = np.cross(A,B)
print(C)

theta = np.arccos(np.dot(A,C)/(np.linalg.norm(A)*np.linalg.norm(C)))
print("rad:", theta, "degree", theta*180/np.pi)


Dot Product
python only calculate dot in vectors!! Use 1-D array
54
Cross Product
[  2 -16  10]
rad: 1.5707963267948966 degree 90.0


## Calculating the angle between vectors
- angle = arccos(A dot B / mag(A)mag(B))

In [27]:
theta = np.arccos(np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B)))
print("rad:", theta, "degree", theta*180/np.pi)

rad: 0.3378896111658608 degree 19.35964866112028
